import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  healthHappinessSidebar: [{type: 'autogenerated', dirName: '01-健康幸福'}],
  careerSuccessSidebar: [{type: 'autogenerated', dirName: '02-事业有成'}],
  securityEngineeringSidebar: [{type: 'autogenerated', dirName: '02-事业有成/01-安全工程'}],
  softwareEngineeringSidebar: [{type: 'autogenerated', dirName: '02-事业有成/02-软件工程'}],
  aiSidebar: [{type: 'autogenerated', dirName: '02-事业有成/03-人工智能'}],
  aiSecuritySidebar: [{type: 'autogenerated', dirName: '02-事业有成/04-AI安全'}],
  careerJobSidebar: [{type: 'autogenerated', dirName: '02-事业有成/05-职业与事业'}],
  financeFreedomSidebar: [{type: 'autogenerated', dirName: '03-财务自由'}],
  workSavingsSidebar: [{type: 'autogenerated', dirName: '03-财务自由/01-储蓄'}],
  expenseControlSidebar: [{type: 'autogenerated', dirName: '03-财务自由/02-支出'}],
  investmentSidebar: [{type: 'autogenerated', dirName: '03-财务自由/03-投资'}],
  insuranceSidebar: [{type: 'autogenerated', dirName: '03-财务自由/04-保险'}],
  exploreWorldSidebar: [{type: 'autogenerated', dirName: '04-人生丰富'}],
  readingSidebar: [{type: 'autogenerated', dirName: '04-人生丰富/01-阅读'}],
  filmSidebar: [{type: 'autogenerated', dirName: '04-人生丰富/02-影视'}],
  travelSidebar: [{type: 'autogenerated', dirName: '04-人生丰富/03-旅行'}],
  musicSidebar: [{type: 'autogenerated', dirName: '04-人生丰富/04-音乐'}],
  miscHobbiesSidebar: [{type: 'autogenerated', dirName: '04-人生丰富/05-杂项爱好'}],
  aboutSidebar: [{type: 'autogenerated', dirName: '05-吴飞飞'}],
  aboutMeSidebar: [{type: 'autogenerated', dirName: '05-吴飞飞/01-关于'}],
  lifeProgressSidebar: ['吴飞飞/三省吾身'],
  annualReviewSidebar: [{type: 'autogenerated', dirName: '05-吴飞飞/02-年度总结'}],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
