import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  lifeFoundationsSidebar: [{type: 'autogenerated', dirName: '02-人生系统/00-万事可成'}],
  // By default, Docusaurus generates a sidebar from the docs folder structure
  healthHappinessSidebar: [{type: 'autogenerated', dirName: '02-人生系统/01-健康幸福'}],
  careerSuccessSidebar: [
    '人生系统/事业有成/事业有成',
    '人生系统/事业有成/职业与事业',
    {type: 'autogenerated', dirName: '02-人生系统/02-事业有成/02-成为专家'},
    {type: 'autogenerated', dirName: '02-人生系统/02-事业有成/03-拿到结果'},
    {type: 'autogenerated', dirName: '02-人生系统/02-事业有成/04-影响协作'},
    {type: 'autogenerated', dirName: '02-人生系统/02-事业有成/05-管理团队'},
    '人生系统/事业有成/领导力',
    '人生系统/事业有成/创建事业',
    {type: 'autogenerated', dirName: '02-人生系统/02-事业有成/07-思维'},
  ],
  securityEngineeringSidebar: [{type: 'autogenerated', dirName: '01-网络安全/01-网络空间安全'}],
  aiSecuritySidebar: [{type: 'autogenerated', dirName: '01-网络安全/02-人工智能安全'}],
  financeFreedomSidebar: [{type: 'autogenerated', dirName: '02-人生系统/03-财务自由'}],
  exploreWorldSidebar: [{type: 'autogenerated', dirName: '02-人生系统/04-人生丰富'}],
  aboutSidebar: [{type: 'autogenerated', dirName: '05-吴飞飞'}],
  aboutMeSidebar: [{type: 'autogenerated', dirName: '05-吴飞飞/01-关于'}],
  lifeProgressSidebar: ['吴飞飞/三省吾身'],
  annualReviewSidebar: [{type: 'autogenerated', dirName: '05-吴飞飞/02-年度总结'}],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
