import type {Audio} from 'aplayer';
import {localLyricsFileByAudioFile} from './localLyrics';

export type PlaylistGroup = {
  id: string;
  label: string;
  tracks: Audio[];
};

export type PlaylistManifestTrack = {
  title: string;
  artist: string;
  source_url: string;
  local_path: string;
};

export type PlaylistManifestGroup = {
  id: string;
  label: string;
  tracks: PlaylistManifestTrack[];
};

const defaultCover = '/music/feei-site-theme-cover.webp';
const defaultTheme = '#205d3b';

const toEncodedUrl = (path: string): string => {
  const normalizedPath = path.replace(/^\/+/, '').replace(/^static\//, '');
  const encodedPath = normalizedPath
    .split('/')
    .filter(Boolean)
    .map((segment) => encodeURIComponent(segment))
    .join('/');

  return `/${encodedPath}`;
};

const localTrack = (name: string, artist: string, fileName: string): Audio => {
  const lyricFileName = localLyricsFileByAudioFile[fileName];

  return {
    name,
    artist,
    url: toEncodedUrl(`music/${fileName}`),
    ...(lyricFileName ? {lrc: toEncodedUrl(`music/${lyricFileName}`)} : {}),
    cover: defaultCover,
    theme: defaultTheme,
  };
};

export const playlistGroupFromManifest = (group: PlaylistManifestGroup): PlaylistGroup => ({
  id: group.id,
  label: group.label,
  tracks: group.tracks.map((track) => ({
    name: track.title,
    artist: track.artist,
    url: toEncodedUrl(track.local_path),
    cover: defaultCover,
    theme: defaultTheme,
  })),
});

const favoriteTracks: Audio[] = [
  // 我喜欢的音乐
  localTrack('我是真的爱上你', '王杰', '我是真的爱上你-王杰.mp3'),
  localTrack('我走后', 'ycccc', '我走后.mp3'),
  localTrack('只对你有感觉', '飞轮海&田馥甄', '只对你有感觉.mp3'),
  localTrack('你就不要想起我', '田馥甄', '你就不要想起我.mp3'),
  localTrack('魔鬼中的天使', '田馥甄', '魔鬼中的天使.mp3'),
  localTrack('我知道', 'BY2', '我知道.mp3'),
  localTrack('忘记时间', '胡歌', '忘记时间-胡歌.mp3'),
  localTrack('等一分钟', '徐誉滕', '等一分钟-徐誉滕.mp3'),
  localTrack('别怕我伤心', '张信哲', '别怕我伤心-张信哲.mp3'),
  localTrack('乌兰巴托的夜', '半吨兄弟&张茜', '乌兰巴托的夜-半吨兄弟张茜.mp3'),
  localTrack('黄梅戏', '慕容晓晓', '黄梅戏-慕容晓晓.mp3'),
  localTrack('Plain Jane', 'A$AP Ferg&Nicki Minaj', 'Plain-Jane-AAP-FergNicki-Minaj.mp3'),
  localTrack('广岛之恋', '莫文蔚', '广岛之恋-莫文蔚.mp3'),
  localTrack('这世界这么多人', '莫文蔚', '这世界那么多人-莫文蔚.mp3'),
  localTrack('差不多先生', '热狗', '差不多先生-热狗.mp3'),
  localTrack('爱我别走', '张震岳', '爱我别走-张震岳.mp3'),
  localTrack('再见', '张震岳', '再见-张震岳.mp3'),
  localTrack('爱的初体验', '张震岳', '爱的初体验-张震岳.mp3'),
  localTrack('思念是一种病', '张震岳&蔡健雅', '思念是一种病-张震岳蔡健雅.mp3'),
  localTrack('坠落', '蔡健雅', '坠落-蔡健雅.mp3'),
  localTrack('寂寞寂寞不好', '曹格', '寂寞寂寞不好-曹格.mp3'),
  localTrack('跳楼机', '利比', '跳楼机-利比.mp3'),
  localTrack('开始懂了', '孙燕姿', '开始懂了-孙燕姿.mp3'),
  localTrack('我怀念的', '孙燕姿', '我怀念的-孙燕姿.mp3'),
  localTrack('遇见', '孙燕姿', '遇见-孙燕姿.mp3'),
  localTrack('就是爱你', '陶喆', '就是爱你-陶喆.mp3'),
  localTrack('爱很简单', '陶喆', '爱很简单-陶喆.mp3'),
  localTrack('往后余生', '马良&孙茜茹', '往后余生-马良孙茜茹.mp3'),
  localTrack('谁', '洋澜一', '谁-洋澜一.mp3'),
  localTrack('年轮', '张碧晨', '年轮-张碧晨.mp3'),
  localTrack('把回忆拼好给你', 'cici_', '把回忆拼好给你-cici_.mp3'),
  localTrack('冬天的秘密', '周传雄', '冬天的秘密-周传雄.mp3'),
  localTrack('可不可以', '张紫豪', '可不可以-张紫豪.mp3'),
  localTrack('如果爱忘了', '旺仔小乔', '如果爱忘了-旺仔小乔.mp3'),
  localTrack('还有我', '任贤齐', '还有我-任贤齐.mp3'),
  localTrack('小宇', '张震岳', '小宇-张震岳.mp3'),
  localTrack('最后一页', '姚晓棠', '最后一页-姚晓棠.mp3'),
  localTrack('关山酒', '等什么君', '关山酒-等什么君.mp3'),
  localTrack('须尽欢', '郑浩', '须尽欢-郑浩.mp3'),
  localTrack('The Nights', 'Avicii', 'The-Nights.mp3'),
  localTrack('いつも何度でも', '宗次郎', 'いつも何度でも.mp3'),
  localTrack('愛にできることはまだあるかい', 'RADWIMPS', '愛にできることはまだあるかい.mp3'),
  localTrack('夢灯籠', 'RADWIMPS', '夢灯籠.mp3'),
  localTrack('三葉のテーマ', 'RADWIMPS', '三葉のテーマ.mp3'),
  localTrack('笔记', '周笔畅', '笔记-周笔畅.mp3'),
  localTrack('如愿', '王菲', '如愿-王菲.mp3'),
  localTrack('体面', '于文文', '体面-于文文.mp3'),
  localTrack('海底', '凤凰传奇', '海底-凤凰传奇.mp3'),
  localTrack('童年', '张艾嘉', '童年.mp3'),
  localTrack('东西', '林俊呈', '东西-林俊呈.mp3'),
  localTrack('卜卦', '崔子格', '卜卦-崔子格.mp3'),
  localTrack('后来', '刘若英', '后来-刘若英.mp3'),
  localTrack('黄昏', '周传雄', '黄昏-周传雄.mp3'),
  localTrack('房间', '刘瑞琦', '房间.mp3'),
  localTrack('青花', '周传雄', '青花-周传雄.mp3'),
  localTrack('勇气', '梁静茹', '勇气-梁静茹.mp3'),
  localTrack('宁夏', '梁静茹', '宁夏-梁静茹.mp3'),
  localTrack('泡沫', '邓紫棋', '泡沫-邓紫棋.mp3'),
  localTrack('城府', '许嵩', '城府-许嵩.mp3'),
  localTrack('素颜', '许嵩', '素颜-许嵩.mp3'),
  localTrack('幻听', '许嵩', '幻听-许嵩.mp3'),
  localTrack('逍遥叹', '胡歌', '逍遥叹.mp3'),
  localTrack('第一次', '房东的猫&戴羽彤', '第一次-房东的猫戴羽彤.mp3'),
  localTrack('起风了', '买辣椒也用券', '起风了-买辣椒也用券.mp3'),
  localTrack('春庭雪', '等什么君', '春庭雪-寒情.mp3'),
  localTrack('猜不透', '丁当', '猜不透-丁当.mp3'),
  localTrack('不怪她', '马思唯', '不怪她-马思唯.mp3'),
  localTrack('一笑江湖', '临渊不羡鱼', '一笑江湖-临渊不羡鱼.mp3'),
  localTrack('忽然之间', '莫文蔚', '忽然之间.mp3'),
  localTrack('我们的歌', '王力宏', '王力宏-我们的歌.mp3'),
  localTrack('无名的人', '孙楠', '无名的人-孙楠.mp3'),
  localTrack('个人简介', '安全着陆', '个人简介-安全着陆.mp3'),
  localTrack('此生不换', '青鸟飞鱼', '此生不换-青鸟飞鱼.mp3'),
  localTrack('有何不可', '许嵩', '有何不可-许嵩.mp3'),
  localTrack('孤单心事', '蓝又时', '孤单心事-蓝又时.mp3'),
  localTrack('铁血丹心', '罗文，甄妮', '铁血丹心.mp3'),
  localTrack('红色石头', '李智楠', '红色石头.mp3'),
  localTrack('我欲乘风', '安全着落', '我欲乘风-安全着陆.mp3'),
  localTrack('回到未来', 'Double Zhuo & Tizzy T', '回到未来-DoubleZhuoTizzyT.mp3'),
  localTrack('电台情歌', '莫文蔚', '电台情歌.mp3'),
  localTrack('清明雨上', '许嵩', '清明雨上-许嵩.mp3'),
  localTrack('需要人陪', '王力宏', '需要人陪.mp3'),
  localTrack('灰色头像', '许嵩', '灰色头像-许嵩.mp3'),
  localTrack('纸短情长', '烟把儿', '纸短情长.mp3'),
  localTrack('一生所爱', '卢冠廷&莫文蔚', '一生所爱-卢冠廷莫文蔚.mp3'),
  localTrack('平凡之路', '后会无期', '平凡之路.mp3'),
  localTrack('漫步人生路', '邓丽君', '漫步人生路-邓丽君.mp3'),
  localTrack('盛夏的果实', '莫文蔚', '盛夏的果实-莫文蔚.mp3'),
  localTrack('小手拉大手', '梁静茹', '小手拉大手-梁静茹.mp3'),
  localTrack('每个人都会', '方大同', '每个人都会-方大同.mp3'),
  localTrack('红色高跟鞋', '蔡健雅', '红色高跟鞋-蔡健雅.mp3'),
  localTrack('多余的解释', '许嵩', '多余的解释-许嵩.mp3'),
  localTrack('最好的安排', '曲婉婷', '最好的安排-曲婉婷.mp3'),
  localTrack('爱就一个字', '张信哲', '爱就一个字.mp3'),
  localTrack('可惜不是你', '梁静茹', '可惜不是你-梁静茹.mp3'),
  localTrack('会呼吸的痛', '梁静茹', '会呼吸的痛-梁静茹.mp3'),
  localTrack('玫瑰花的葬礼', '许嵩', '玫瑰花的葬礼-许嵩.mp3'),
  localTrack('有没有人告诉你', '陈楚生', '有没有人告诉你-陈楚生.mp3'),
  localTrack('最远的你是我最近的爱', '车继铃', '最远的你是我最近的爱.mp3'),
  localTrack('总有一天你会在我身边', '棱境', '总有一天你会在我身边-棱境.mp3'),
  localTrack('APT', 'ROSÉ & Bruno Mars', 'ROSE-Bruno-Mars-APT.mp3'),
  localTrack('Time', '小青龙 & 辉子', 'Time-小青龙辉子.mp3'),
  localTrack('August', 'Intelligency', 'August-Intelligency.mp3'),
  localTrack('Don\'t matter', 'Akon', 'Dont-Matter-Akon.mp3'),
  localTrack('Free Loop', 'Daniel Powter', 'freeloop.mp3'),
  localTrack('Jar of Love', '曲婉婷', 'jaroflove-曲婉婷.mp3'),
  localTrack('Plain Jane', 'A$AP Ferg&Nicki Minaj', 'Plain-JaneRemix-AAP-FergNicki-Minaj.mp3-.mp3'),
  localTrack('Thank You', 'Dido', 'Thank-You-Dido.mp3'),
  localTrack('I miss you', '罗百吉', 'IMissYou-罗百吉.mp3'),
  localTrack('See You Again', 'Wiz Khalifa&Charlie Puth ', 'SeeYouAgain-WizKhalifaCharliePuth.mp3'),
  localTrack('Rage Your Dream', 'm.o.v.e', 'Rage-Your-Dream-m.o.v.e.mp3'),
  localTrack('Welcome to New York', 'Taylor Swift', 'Welcome-to-new-york.mp3'),

];

const jayTracks: Audio[] = [
  localTrack('Mine Mine', '周杰伦', '周杰伦/MineMine.wav'),
  localTrack('一路向北', '周杰伦', '周杰伦/一路向北.wav'),
  localTrack('七里香', '周杰伦', '周杰伦/七里香.wav'),
  localTrack('三年二班', '周杰伦', '周杰伦/三年二班.wav'),
  localTrack('上海一九四三', '周杰伦', '周杰伦/上海一九四三.wav'),
  localTrack('不能说的秘密', '周杰伦', '周杰伦/不能说的秘密.wav'),
  localTrack('世界末日', '周杰伦', '周杰伦/世界末日.wav'),
  localTrack('东风破', '周杰伦', '周杰伦/东风破.wav'),
  localTrack('乌克丽丽', '周杰伦', '周杰伦/乌克丽丽.wav'),
  localTrack('乔克叔叔', '周杰伦', '周杰伦/乔克叔叔.wav'),
  localTrack('乱舞春秋', '周杰伦', '周杰伦/乱舞春秋.wav'),
  localTrack('以父之名', '周杰伦', '周杰伦/以父之名.wav'),
  localTrack('伊斯坦堡', '周杰伦', '周杰伦/伊斯坦堡.wav'),
  localTrack('你听得到', '周杰伦', '周杰伦/你听得到.wav'),
  localTrack('你好吗', '周杰伦', '周杰伦/你好吗.wav'),
  localTrack('你比从前快乐', '周杰伦', '周杰伦/你比从前快乐.wav'),
  localTrack('倒带', '周杰伦', '周杰伦/倒带.wav'),
  localTrack('借口', '周杰伦', '周杰伦/借口.wav'),
  localTrack('免费教学录影带', '周杰伦', '周杰伦/免费教学录影带.wav'),
  localTrack('公主病', '周杰伦', '周杰伦/公主病.wav'),
  localTrack('公公偏头疼', '周杰伦', '周杰伦/公公偏头疼.wav'),
  localTrack('兰亭序', '周杰伦', '周杰伦/兰亭序.wav'),
  localTrack('分裂', '周杰伦', '周杰伦/分裂.wav'),
  localTrack('千山万水', '周杰伦', '周杰伦/千山万水.wav'),
  localTrack('千里之外', '周杰伦', '周杰伦/千里之外.wav'),
  localTrack('半兽人', '周杰伦', '周杰伦/半兽人.wav'),
  localTrack('半岛铁盒', '周杰伦', '周杰伦/半岛铁盒.wav'),
  localTrack('印地安老斑鸠', '周杰伦', '周杰伦/印地安老斑鸠.wav'),
  localTrack('印第安老斑鸠', '周杰伦', '周杰伦/印第安老斑鸠.wav'),
  localTrack('双刀', '周杰伦', '周杰伦/双刀.wav'),
  localTrack('双节棍', '周杰伦', '周杰伦/双节棍.wav'),
  localTrack('反方向的钟', '周杰伦', '周杰伦/反方向的钟.wav'),
  localTrack('发如雪', '周杰伦', '周杰伦/发如雪.wav'),
  localTrack('可爱女人', '周杰伦', '周杰伦/可爱女人.wav'),
  localTrack('同一种调调', '周杰伦', '周杰伦/同一种调调.wav'),
  localTrack('听妈妈的话', '周杰伦', '周杰伦/听妈妈的话.wav'),
  localTrack('哪里都是你', '周杰伦', '周杰伦/哪里都是你.wav'),
  localTrack('嘻哈空姐', '周杰伦', '周杰伦/嘻哈空姐.wav'),
  localTrack('四季列车', '周杰伦', '周杰伦/四季列车.wav'),
  localTrack('四面楚歌', '周杰伦', '周杰伦/四面楚歌.wav'),
  localTrack('回到过去', '周杰伦', '周杰伦/回到过去.wav'),
  localTrack('园游会', '周杰伦', '周杰伦/园游会.wav'),
  localTrack('困兽之斗', '周杰伦', '周杰伦/困兽之斗.wav'),
  localTrack('外婆', '周杰伦', '周杰伦/外婆.wav'),
  localTrack('夜曲', '周杰伦', '周杰伦/夜曲.wav'),
  localTrack('夜的第七章', '周杰伦', '周杰伦/夜的第七章.wav'),
  localTrack('大笨钟', '周杰伦', '周杰伦/大笨钟.wav'),
  localTrack('她的睫毛', '周杰伦', '周杰伦/她的睫毛.wav'),
  localTrack('好久不见', '周杰伦', '周杰伦/好久不见.wav'),
  localTrack('威廉古堡', '周杰伦', '周杰伦/威廉古堡.wav'),
  localTrack('娘子', '周杰伦', '周杰伦/娘子.wav'),
  localTrack('安静', '周杰伦', '周杰伦/安静.wav'),
  localTrack('完美主义', '周杰伦', '周杰伦/完美主义.wav'),
  localTrack('对不起', '周杰伦', '周杰伦/对不起.wav'),
  localTrack('将军', '周杰伦', '周杰伦/将军.wav'),
  localTrack('开不了口', '周杰伦', '周杰伦/开不了口.wav'),
  localTrack('心雨', '周杰伦', '周杰伦/心雨.wav'),
  localTrack('忍者', '周杰伦', '周杰伦/忍者.wav'),
  localTrack('惊叹号', '周杰伦', '周杰伦/惊叹号.wav'),
  localTrack('愛在西元前', '周杰伦', '周杰伦/愛在西元前.wav'),
  localTrack('懦夫', '周杰伦', '周杰伦/懦夫.wav'),
  localTrack('我不配', '周杰伦', '周杰伦/我不配.wav'),
  localTrack('我的地盘', '周杰伦', '周杰伦/我的地盘.wav'),
  localTrack('我落泪·情绪零落', '周杰伦', '周杰伦/我落泪·情绪零落.wav'),
  localTrack('手语', '周杰伦', '周杰伦/手语.wav'),
  localTrack('扯', '周杰伦', '周杰伦/扯.wav'),
  localTrack('搁浅', '周杰伦', '周杰伦/搁浅.wav'),
  localTrack('斗牛', '周杰伦', '周杰伦/斗牛.wav'),
  localTrack('断了的弦', '周杰伦', '周杰伦/断了的弦.wav'),
  localTrack('无双', '周杰伦', '周杰伦/无双.wav'),
  localTrack('时光机', '周杰伦', '周杰伦/时光机.wav'),
  localTrack('明明就', '周杰伦', '周杰伦/明明就.wav'),
  localTrack('星晴', '周杰伦', '周杰伦/星晴.wav'),
  localTrack('晴天', '周杰伦', '周杰伦/晴天.wav'),
  localTrack('暗号', '周杰伦', '周杰伦/暗号.wav'),
  localTrack('最后的战役', '周杰伦', '周杰伦/最后的战役.wav'),
  localTrack('最长的电影', '周杰伦', '周杰伦/最长的电影.wav'),
  localTrack('本草纲目', '周杰伦', '周杰伦/本草纲目.wav'),
  localTrack('刀马旦', '周杰伦 & 李玟', '周杰伦/李玟-刀马旦.wav'),
  localTrack('枫', '周杰伦', '周杰伦/枫.wav'),
  localTrack('比较大的大提琴', '周杰伦 & 梁心颐 & 杨瑞代', '周杰伦/梁心颐&杨瑞代-比较大的大提琴.wav'),
  localTrack('梦想启动', '周杰伦', '周杰伦/梦想启动.wav'),
  localTrack('梯田', '周杰伦', '周杰伦/梯田.wav'),
  localTrack('止战之殇', '周杰伦', '周杰伦/止战之殇.wav'),
  localTrack('水手怕水', '周杰伦', '周杰伦/水手怕水.wav'),
  localTrack('流浪诗人', '周杰伦', '周杰伦/流浪诗人.wav'),
  localTrack('浪漫手机', '周杰伦', '周杰伦/浪漫手机.wav'),
  localTrack('漂移', '周杰伦', '周杰伦/漂移.wav'),
  localTrack('火车叨位去', '周杰伦', '周杰伦/火车叨位去.wav'),
  localTrack('烟花易冷', '周杰伦', '周杰伦/烟花易冷.wav'),
  localTrack('爱情悬崖', '周杰伦', '周杰伦/爱情悬崖.wav'),
  localTrack('爱我别走', '周杰伦', '周杰伦/爱我别走.wav'),
  localTrack('爱的飞行日记', '周杰伦', '周杰伦/爱的飞行日记.wav'),
  localTrack('爷爷泡的茶', '周杰伦', '周杰伦/爷爷泡的茶.wav'),
  localTrack('爸我回来了', '周杰伦', '周杰伦/爸我回来了.wav'),
  localTrack('牛仔很忙', '周杰伦', '周杰伦/牛仔很忙.wav'),
  localTrack('献世', '周杰伦', '周杰伦/献世.wav'),
  localTrack('珊瑚海', '周杰伦', '周杰伦/珊瑚海.wav'),
  localTrack('琴伤', '周杰伦', '周杰伦/琴伤.wav'),
  localTrack('瓦解', '周杰伦', '周杰伦/瓦解.wav'),
  localTrack('甜甜的', '周杰伦', '周杰伦/甜甜的.wav'),
  localTrack('电影大灌篮原声', '周杰伦', '周杰伦/电影大灌篮原声.wav'),
  localTrack('疗伤烧肉粽', '周杰伦', '周杰伦/疗伤烧肉粽.wav'),
  localTrack('白色风车', '周杰伦', '周杰伦/白色风车.wav'),
  localTrack('皮影戏', '周杰伦', '周杰伦/皮影戏.wav'),
  localTrack('离开', '周杰伦', '周杰伦/离开.wav'),
  localTrack('稻香', '周杰伦', '周杰伦/稻香.wav'),
  localTrack('简单爱', '周杰伦', '周杰伦/简单爱.wav'),
  localTrack('米兰的小铁匠', '周杰伦', '周杰伦/米兰的小铁匠.wav'),
  localTrack('红模仿', '周杰伦', '周杰伦/红模仿.wav'),
  localTrack('给我一首歌的时间', '周杰伦', '周杰伦/给我一首歌的时间.wav'),
  localTrack('自导自演', '周杰伦', '周杰伦/自导自演.wav'),
  localTrack('花海', '周杰伦', '周杰伦/花海.wav'),
  localTrack('菊花台', '周杰伦', '周杰伦/菊花台.wav'),
  localTrack('蒲公英的约定', '周杰伦', '周杰伦/蒲公英的约定.wav'),
  localTrack('蓝色风暴', '周杰伦', '周杰伦/蓝色风暴.wav'),
  localTrack('蛇舞', '周杰伦', '周杰伦/蛇舞.wav'),
  localTrack('蜗牛', '周杰伦', '周杰伦/蜗牛.wav'),
  localTrack('说了再见', '周杰伦', '周杰伦/说了再见.wav'),
  localTrack('说好的幸福呢', '周杰伦', '周杰伦/说好的幸福呢.wav'),
  localTrack('超人不会飞', '周杰伦', '周杰伦/超人不会飞.wav'),
  localTrack('超跑女神', '周杰伦', '周杰伦/超跑女神.wav'),
  localTrack('跨时代', '周杰伦', '周杰伦/跨时代.wav'),
  localTrack('跨時代', '周杰伦', '周杰伦/跨時代.wav'),
  localTrack('轨迹', '周杰伦', '周杰伦/轨迹.wav'),
  localTrack('迷迭香', '周杰伦', '周杰伦/迷迭香.wav'),
  localTrack('迷魂曲', '周杰伦', '周杰伦/迷魂曲.wav'),
  localTrack('退后', '周杰伦', '周杰伦/退后.wav'),
  localTrack('逆鳞', '周杰伦', '周杰伦/逆鳞.wav'),
  localTrack('阳光宅男', '周杰伦', '周杰伦/阳光宅男.wav'),
  localTrack('雨下一整晚', '周杰伦', '周杰伦/雨下一整晚.wav'),
  localTrack('霍元甲', '周杰伦', '周杰伦/霍元甲.wav'),
  localTrack('青花瓷', '周杰伦', '周杰伦/青花瓷.wav'),
  localTrack('飘移', '周杰伦', '周杰伦/飘移.wav'),
  localTrack('魔术先生', '周杰伦', '周杰伦/魔术先生.wav'),
  localTrack('麦芽糖', '周杰伦', '周杰伦/麦芽糖.wav'),
  localTrack('黄金甲', '周杰伦', '周杰伦/黄金甲.wav'),
  localTrack('黑色幽默', '周杰伦', '周杰伦/黑色幽默.wav'),
  localTrack('黑色毛衣', '周杰伦', '周杰伦/黑色毛衣.wav'),
  localTrack('龙卷风', '周杰伦', '周杰伦/龙卷风.wav'),
  localTrack('龙战骑士', '周杰伦', '周杰伦/龙战骑士.wav'),
  localTrack('龙拳', '周杰伦', '周杰伦/龙拳.wav'),
  localTrack('懦夫', '周杰伦 & 余妮', '周杰伦/余妮-懦夫.wav'),
  localTrack('珊瑚海', '周杰伦 & 梁心颐', '周杰伦/梁心颐-珊瑚海.wav'),
  localTrack('千里之外', '周杰伦 & 费玉清', '周杰伦/费玉清-千里之外.wav'),
  localTrack('傻笑', '周杰伦 & 袁咏琳', '周杰伦/袁咏琳-傻笑.wav'),
  localTrack('禁止悲伤', '周杰伦 & 许茹芸', '周杰伦/许茹芸-禁止悲伤.wav'),
  localTrack('屋顶', '周杰伦 & 温岚', '周杰伦/温岚-屋顶.wav'),
];

const ambientTracks: Audio[] = [
  // 白噪音
  localTrack('雨声', '未知', '雨声.mp3'),
  localTrack('水流声1', 'BBC', 'bbc_water-gen_07031094.mp3'),
  localTrack('烟花声2', 'BBC', 'bbc_bonfires-_07019119.mp3'),
  localTrack('烟花声1', 'BBC', 'bbc_fireworks-_07019117.mp3'),
  localTrack('蝉鸣声1', 'BBC', 'bbc_desert-atm_nhu9327601.mp3'),
  localTrack('火焰声1', 'BBC', 'bbc_household-_07002052.mp3'),
  localTrack('鸟叫声5', 'BBC', 'bbc_birds-bla_07051151.mp3'),
  localTrack('鸟叫声4', 'BBC', 'bbc_deciduous-_nhu0509405.mp3'),
  localTrack('鸟叫声3', 'BBC', 'bbc_mixed-wood_nhu0509415.mp3'),
  localTrack('鸟叫声2', 'BBC', 'bbc_moorland-_nhu0510424.mp3'),
  localTrack('鸟叫声1', 'BBC', 'bbc_tropical-s_nhu0501109.mp3'),
];

export const siteMusicGroups: PlaylistGroup[] = [
  {
    id: 'favorites',
    label: '我喜欢的音乐',
    tracks: favoriteTracks,
  },
  {
    id: 'jay',
    label: '周杰伦',
    tracks: jayTracks,
  },
  {
    id: 'ambient',
    label: '白噪音',
    tracks: ambientTracks,
  },
];

export const siteMusicPlaylist: Audio[] = favoriteTracks;
