#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SOURCE="$ROOT/AI.md"
AGENTS="$ROOT/AGENTS.md"
CLAUDE="$ROOT/CLAUDE.md"

if [[ ! -f "$SOURCE" ]]; then
  echo "Missing source file: $SOURCE" >&2
  exit 1
fi

cat > "$AGENTS" <<'EOF'
# AGENTS.md

This file is generated from `AI.md`.
Do not edit this file directly. Edit `AI.md` instead.

Codex must read and follow `AI.md` before making changes.

EOF

cat "$SOURCE" >> "$AGENTS"

cat > "$CLAUDE" <<'EOF'
# CLAUDE.md

This file is generated from `AI.md`.
Do not edit this file directly. Edit `AI.md` instead.

Claude Code must read and follow `AI.md` at the start of each task.

EOF

cat "$SOURCE" >> "$CLAUDE"

echo "Synced AGENTS.md and CLAUDE.md from AI.md"
